services:
  - type: web
    name: hrms-backend
    runtime: python
    pythonVersion: "3.11.0"
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: HR_EMAIL
        sync: false